export const gameConstants = {
  SHOW_REQUEST: 'SHOW_GAME_REQUEST',
  SHOW_SUCCESS: 'SHOW_GAME_SUCCESS',
  SHOW_FAILURE: 'SHOW_GAME_FAILURE',

  CREATE_GOAL_REQUEST: 'CREATE_GAME_GOAL_REQUEST',
  CREATE_GOAL_SUCCESS: 'CREATE_GAME_GOAL_SUCCESS',
  CREATE_GOAL_FAILURE: 'CREATE_GAME_GOAL_FAILURE',

  UPDATE_GOAL_REQUEST: 'UPDATE_GAME_GOAL_REQUEST',
  UPDATE_GOAL_SUCCESS: 'UPDATE_GAME_GOAL_SUCCESS',
  UPDATE_GOAL_FAILURE: 'UPDATE_GAME_GOAL_FAILURE',

  DESTROY_GOAL_REQUEST: 'DESTROY_GAME_GOAL_REQUEST',
  DESTROY_GOAL_SUCCESS: 'DESTROY_GAME_GOAL_SUCCESS',
  DESTROY_GOAL_FAILURE: 'DESTROY_GAME_GOAL_FAILURE',

  CREATE_PENALTY_REQUEST: 'CREATE_GAME_PENALTY_REQUEST',
  CREATE_PENALTY_SUCCESS: 'CREATE_GAME_PENALTY_SUCCESS',
  CREATE_PENALTY_FAILURE: 'CREATE_GAME_PENALTY_FAILURE',

  UPDATE_PENALTY_REQUEST: 'UPDATE_GAME_PENALTY_REQUEST',
  UPDATE_PENALTY_SUCCESS: 'UPDATE_GAME_PENALTY_SUCCESS',
  UPDATE_PENALTY_FAILURE: 'UPDATE_GAME_PENALTY_FAILURE',

  DESTROY_PENALTY_REQUEST: 'DESTROY_GAME_PENALTY_REQUEST',
  DESTROY_PENALTY_SUCCESS: 'DESTROY_GAME_PENALTY_SUCCESS',
  DESTROY_PENALTY_FAILURE: 'DESTROY_GAME_PENALTY_FAILURE',

  ADD_PLAYER_REQUEST: 'ADD_GAME_PLAYER_REQUEST',
  ADD_PLAYER_SUCCESS: 'ADD_GAME_PLAYER_SUCCESS',
  ADD_PLAYER_FAILURE: 'ADD_GAME_PLAYER_FAILURE',

  REMOVE_PLAYER_REQUEST: 'REMOVE_GAME_PLAYER_REQUEST',
  REMOVE_PLAYER_SUCCESS: 'REMOVE_GAME_PLAYER_SUCCESS',
  REMOVE_PLAYER_FAILURE: 'REMOVE_GAME_PLAYER_FAILURE'
}