export const playerCodeConstants = {
  CREATE_CODE_REQUEST: 'CREATE_PLAYER_CODE_REQUEST',
  CREATE_CODE_SUCCESS: 'CREATE_PLAYER_CODE_SUCCESS',
  CREATE_CODE_FAILURE: 'CREATE_PLAYER_CODE_FAILURE',

  LINK_PLAYER_REQUEST: 'LINK_USER_PLAYER_REQUEST',
  LINK_PLAYER_SUCCESS: 'LINK_USER_PLAYER_SUCCESS',
  LINK_PLAYER_FAILURE: 'LINK_USER_PLAYER_FAILURE',

  SHOW_CODE_REQUEST: 'SHOW_PLAYER_CODE_REQUEST',
  SHOW_CODE_SUCCESS: 'SHOW_PLAYER_CODE_SUCCESS',
  SHOW_CODE_FAILURE: 'SHOW_PLAYER_CODE_FAILURE'
}