export const seasonConstants = {
  SHOW_REQUEST: 'SHOW_SEASON_REQUEST',
  SHOW_SUCCESS: 'SHOW_SEASON_SUCCESS',
  SHOW_FAILURE: 'SHOW_SEASON_FAILURE',

  CREATE_GAME_REQUEST: 'CREATE_SEASON_GAME_REQUEST',
  CREATE_GAME_SUCCESS: 'CREATE_SEASON_GAME_SUCCESS',
  CREATE_GAME_FAILURE: 'CREATE_SEASON_GAME_FAILURE',

  UPDATE_GAME_REQUEST: 'UPDATE_SEASON_GAME_REQUEST',
  UPDATE_GAME_SUCCESS: 'UPDATE_SEASON_GAME_SUCCESS',
  UPDATE_GAME_FAILURE: 'UPDATE_SEASON_GAME_FAILURE',

  DESTROY_GAME_REQUEST: 'DESTROY_SEASON_GAME_REQUEST',
  DESTROY_GAME_SUCCESS: 'DESTROY_SEASON_GAME_SUCCESS',
  DESTROY_GAME_FAILURE: 'DESTROY_SEASON_GAME_FAILURE'
}