export const teamsConstants = {
  INDEX_REQUEST: 'TEAMS_INDEX_REQUEST',
  INDEX_SUCCESS: 'TEAMS_INDEX_SUCCESS',
  INDEX_FAILURE: 'TEAMS_INDEX_FAILURE',

  SHOW_REQUEST: 'TEAMS_SHOW_REQUEST',
  SHOW_SUCCESS: 'TEAMS_SHOW_SUCCESS',
  SHOW_FAILURE: 'TEAMS_SHOW_FAILURE',

  CREATE_REQUEST: 'TEAMS_CREATE_REQUEST',
  CREATE_SUCCESS: 'TEAMS_CREATE_SUCCESS',
  CREATE_FAILURE: 'TEAMS_CREATE_FAILURE',

  UPDATE_REQUEST: 'TEAMS_UPDATE_REQUEST',
  UPDATE_SUCCESS: 'TEAMS_UPDATE_SUCCESS',
  UPDATE_FAILURE: 'TEAMS_UPDATE_FAILURE',

  DESTROY_REQUEST: 'TEAMS_DESTROY_REQUEST',
  DESTROY_SUCCESS: 'TEAMS_DESTROY_SUCCESS',
  DESTROY_FAILURE: 'TEAMS_DESTROY_FAILURE'
}