export const teamConstants = {
  SHOW_REQUEST: 'TEAM_SHOW_REQUEST',
  SHOW_SUCCESS: 'TEAM_SHOW_SUCCESS',
  SHOW_FAILURE: 'TEAM_SHOW_FAILURE',

  CREATE_SEASON_REQUEST: 'CREATE_TEAM_SEASON_REQUEST',
  CREATE_SEASON_SUCCESS: 'CREATE_TEAM_SEASON_SUCCESS',
  CREATE_SEASON_FAILURE: 'CREATE_TEAM_SEASON_FAILURE',

  UPDATE_SEASON_REQUEST: 'UPDATE_TEAM_SEASON_REQUEST',
  UPDATE_SEASON_SUCCESS: 'UPDATE_TEAM_SEASON_SUCCESS',
  UPDATE_SEASON_FAILURE: 'UPDATE_TEAM_SEASON_FAILURE',

  DESTROY_SEASON_REQUEST: 'DESTROY_TEAM_SEASON_REQUEST',
  DESTROY_SEASON_SUCCESS: 'DESTROY_TEAM_SEASON_SUCCESS',
  DESTROY_SEASON_FAILURE: 'DESTROY_TEAM_SEASON_FAILURE',

  CREATE_PLAYER_REQUEST: 'CREATE_TEAM_PLAYER_REQUEST',
  CREATE_PLAYER_SUCCESS: 'CREATE_TEAM_PLAYER_SUCCESS',
  CREATE_PLAYER_FAILURE: 'CREATE_TEAM_PLAYER_FAILURE',

  UPDATE_PLAYER_REQUEST: 'UPDATE_TEAM_PLAYER_REQUEST',
  UPDATE_PLAYER_SUCCESS: 'UPDATE_TEAM_PLAYER_SUCCESS',
  UPDATE_PLAYER_FAILURE: 'UPDATE_TEAM_PLAYER_FAILURE',

  DESTROY_PLAYER_REQUEST: 'DESTROY_TEAM_PLAYER_REQUEST',
  DESTROY_PLAYER_SUCCESS: 'DESTROY_TEAM_PLAYER_SUCCESS',
  DESTROY_PLAYER_FAILURE: 'DESTROY_TEAM_PLAYER_FAILURE'
}