export const userConstants = {
  LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
  LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
  LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',

  LOGOUT: 'USERS_LOGOUT',

  SIGNUP_REQUEST: 'USERS_SIGNUP_REQUEST',
  SIGNUP_SUCCESS: 'USERS_SIGNUP_SUCCESS',
  SIGNUP_FAILURE: 'USERS_SIGNUP_FAILURE',

  DASHBOARD_REQUEST: 'USERS_DASHBOARD_REQUEST',
  DASHBOARD_SUCCESS: 'USERS_DASHBOARD_SUCCESS',
  DASHBOARD_FAILURE: 'USERS_DASHBOARD_FAILURE'
}